// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Chalk = require("chalk");

function log(prim) {
  console.log(prim);
  return /* () */0;
}

function black(str) {
  return Chalk.black(str);
}

function red(str) {
  return Chalk.red(str);
}

function green(str) {
  return Chalk.green(str);
}

function yellow(str) {
  return Chalk.yellow(str);
}

function blue(str) {
  return Chalk.blue(str);
}

function magenta(str) {
  return Chalk.magenta(str);
}

function cyan(str) {
  return Chalk.cyan(str);
}

function white(str) {
  return Chalk.white(str);
}

function gray(str) {
  return Chalk.gray(str);
}

function redBright(str) {
  return Chalk.redBright(str);
}

function greenBright(str) {
  return Chalk.greenBright(str);
}

function yellowBright(str) {
  return Chalk.yellowBright(str);
}

function blueBright(str) {
  return Chalk.blueBright(str);
}

function magentaBright(str) {
  return Chalk.magentaBright(str);
}

function cyanBright(str) {
  return Chalk.cyanBright(str);
}

function whiteBright(str) {
  return Chalk.whiteBright(str);
}

var Chalk$1 = /* module */[
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* redBright */redBright,
  /* greenBright */greenBright,
  /* yellowBright */yellowBright,
  /* blueBright */blueBright,
  /* magentaBright */magentaBright,
  /* cyanBright */cyanBright,
  /* whiteBright */whiteBright
];

var hello = Chalk.cyanBright("hello");

var concat = Chalk.magenta("there");

console.log(hello + concat);

exports.log    = log;
exports.Chalk  = Chalk$1;
exports.hello  = hello;
exports.concat = concat;
/* hello Not a pure module */
