// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var Chalk = require("chalk");

function black(str) {
  return Chalk.black(str);
}

function red(str) {
  return Chalk.red(str);
}

function green(str) {
  return Chalk.green(str);
}

function yellow(str) {
  return Chalk.yellow(str);
}

function blue(str) {
  return Chalk.blue(str);
}

function magenta(str) {
  return Chalk.magenta(str);
}

function cyan(str) {
  return Chalk.cyan(str);
}

function white(str) {
  return Chalk.white(str);
}

function gray(str) {
  return Chalk.gray(str);
}

function redBright(str) {
  return Chalk.redBright(str);
}

function greenBright(str) {
  return Chalk.greenBright(str);
}

function yellowBright(str) {
  return Chalk.yellowBright(str);
}

function blueBright(str) {
  return Chalk.blueBright(str);
}

function magentaBright(str) {
  return Chalk.magentaBright(str);
}

function cyanBright(str) {
  return Chalk.cyanBright(str);
}

function whiteBright(str) {
  return Chalk.whiteBright(str);
}

function bgBlack(str) {
  return Chalk.bgBlack(str);
}

function bgRed(str) {
  return Chalk.bgRed(str);
}

function bgGreen(str) {
  return Chalk.bgGreen(str);
}

function bgYellow(str) {
  return Chalk.bgYellow(str);
}

function bgBlue(str) {
  return Chalk.bgBlue(str);
}

function bgMagenta(str) {
  return Chalk.bgMagenta(str);
}

function bgCyan(str) {
  return Chalk.bgCyan(str);
}

function bgWhite(str) {
  return Chalk.bgWhite(str);
}

function bgBlackBright(str) {
  return Chalk.bgBlackBright(str);
}

function bgRedBright(str) {
  return Chalk.bgRedBright(str);
}

function bgGreenBright(str) {
  return Chalk.bgGreenBright(str);
}

function bgYellowBright(str) {
  return Chalk.bgYellowBright(str);
}

function bgBlueBright(str) {
  return Chalk.bgBlueBright(str);
}

function bgMagentaBright(str) {
  return Chalk.bgMagentaBright(str);
}

function bgCyanBright(str) {
  return Chalk.bgCyanBright(str);
}

function bgWhiteBright(str) {
  return Chalk.bgWhiteBright(str);
}

function reset(str) {
  return Chalk.reset(str);
}

function bold(str) {
  return Chalk.bold(str);
}

function dim(str) {
  return Chalk.dim(str);
}

function italic(str) {
  return Chalk.italic(str);
}

function underline(str) {
  return Chalk.underline(str);
}

function inverse(str) {
  return Chalk.inverse(str);
}

function hidden(str) {
  return Chalk.hidden(str);
}

function strikethrough(str) {
  return Chalk.strikethrough(str);
}

function visible(str) {
  return Chalk.visible(str);
}

function compose(f, g, x) {
  return Curry._1(f, Curry._1(g, x));
}

function pipe(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function hex(hex$1, str) {
  return Chalk.hex(hex$1, str);
}

var Chalk$1 = /* module */[
  /* black */black,
  /* red */red,
  /* green */green,
  /* yellow */yellow,
  /* blue */blue,
  /* magenta */magenta,
  /* cyan */cyan,
  /* white */white,
  /* gray */gray,
  /* redBright */redBright,
  /* greenBright */greenBright,
  /* yellowBright */yellowBright,
  /* blueBright */blueBright,
  /* magentaBright */magentaBright,
  /* cyanBright */cyanBright,
  /* whiteBright */whiteBright,
  /* bgBlack */bgBlack,
  /* bgRed */bgRed,
  /* bgGreen */bgGreen,
  /* bgYellow */bgYellow,
  /* bgBlue */bgBlue,
  /* bgMagenta */bgMagenta,
  /* bgCyan */bgCyan,
  /* bgWhite */bgWhite,
  /* bgBlackBright */bgBlackBright,
  /* bgRedBright */bgRedBright,
  /* bgGreenBright */bgGreenBright,
  /* bgYellowBright */bgYellowBright,
  /* bgBlueBright */bgBlueBright,
  /* bgMagentaBright */bgMagentaBright,
  /* bgCyanBright */bgCyanBright,
  /* bgWhiteBright */bgWhiteBright,
  /* reset */reset,
  /* bold */bold,
  /* dim */dim,
  /* italic */italic,
  /* underline */underline,
  /* inverse */inverse,
  /* hidden */hidden,
  /* strikethrough */strikethrough,
  /* visible */visible,
  /* compose */compose,
  /* pipe */pipe,
  /* hex */hex
];

exports.Chalk = Chalk$1;
/* chalk Not a pure module */
